version: "2"

services:
  app:
    command: npm start
    environment:
      DEBUG: battleship:*
    image: node:4.4
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
